name: Verify PR with JaCoCo

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21

      - name: Run tests with JaCoCo
        run: mvn clean verify

      - name: Check code coverage
        run: |
          COVERAGE=$(mvn jacoco:report | grep -Po 'LINE\s+TOTAL\s+\K\d+(?=%)')

          echo "Line coverage: $COVERAGE%"

          if [ "$COVERAGE" -lt 80 ]; then
            echo "❌ Code coverage is below 80%!"
            exit 1
          fi
