name: Verify PR with JaCoCo

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21

      - name: Run tests with JaCoCo
        run: mvn clean verify
